from . import migration_config
from . import migration_log
from . import migration_test
from . import migration_fields
from . import migration_models
from . import migration_origin_models
from . import migration_origin_fields
from . import ir_model_fields_inherit
from . import migration_id_mapping